/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghost;

/**
 *
 * @author CLAB_36
 */
public class String1 extends javax.swing.JFrame {

    /**
     * Creates new form String
     */
    public String1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name 1");

        a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name 2");

        b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name 3");

        c.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        d.setColumns(20);
        d.setRows(5);
        jScrollPane1.setViewportView(d);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(a))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String  name1=new String();
name1=a.getText();
String name2=new String();
name2=b.getText();
String name3= new String();
name3=c.getText();

lengthOfString(name1);
characterAtIndex(name1);
compareStrings(name1,name2);
concatination1(name1,name2);
concatination2(name1,name2);
occurrenceOfN(name3);
subString(name3);
replaceCharacter(name3);
caseConversion(name1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void lengthOfString(String name)
    {
        d.append("LENGHT OF STRING");
        d.append("\n-------------\n");
        d.append("Length of String "+name+" is "+name.length());
    }
    public void characterAtIndex(String name)
    {
        d.append("\n\nCHARACTER AT INDEX ");
        d.append("\n-------------\n");
        d.append("At 0 the character is "+name.charAt(0)) ;
        d.append("\n At 3 the character is "+name.charAt(3));
    }
    public void compareStrings(String name1,String name2)
    {
        d.append("\n\nCOMPARE STRINGS\n");
        d.append("-------------\n");
        d.append("Compare "+name1+" and "+name2+"="+name1.compareTo(name2));
        d.append("\nCompare "+name2+" and "+name1+"="+name2.compareTo(name1));
        d.append("\nCompare "+name2+" and "+name1+"="+name2.compareTo(name2));
        d.append("\n"+name1+" and "+name2+" are ");
        if(name1.compareTo(name2)==0)
                {d.append("the same");}
        else
        {
            d.append("not the same");}
        d.append("\nEquals"+name2+"and"+name1+"="+name2.equals(name1));
        d.append("\nEquals"+name2+"and"+name2+"="+name2.equals(name2));
    }
     public void concatination1(String name1,String name2)
    {
        d.append("\n\nCONCATINATION1\n");
        d.append("-------------\n");
        name1=name1.concat(" ");
        name1=name1.concat(name2);
        d.append("name1= "+name1);
    }
     public void concatination2(String name1,String name2)
    {
        d.append("\n\nCONCATINATION2\n");
        d.append("-------------\n");
        name1=name1+" "+name2;
        d.append("name1= "+name1);
    }
     public void occurrenceOfN(String name)
    {
        d.append("\n\nOCCURRENCES OF n");
        d.append("\n------------");
        d.append("\nFirst occureence of 'n' in "+name+" is at index "+name.indexOf('n'));
        d.append("\nLast occurrence of 'n' in "+name+" is at index "+name.lastIndexOf('n'));
        d.append("\nFirst occurrence of 'Z' in "+name+" is at index "+name.indexOf('Z'));
    }
     public void subString(String name1)
    {
        d.append("\n\nSUBSTRINGS");
        d.append("\n------------");
        d.append("\nSubstring from index 4 onward = "+name1.substring(4));
        String name2=name1.substring(0,name1.length());
        d.append("\nEntire copy of "+name1+"="+name2);
        name2=name1.substring(0,2);
        d.append("\n\nSubstring from index 0 to 2 = "+name2);
        name2 = name2.concat(name1.substring(name1.indexOf(' '),name1.indexOf(' ')+3));
        d.append("\nname2 = "+name2);
    }
     public void replaceCharacter(String name)
    {
    d.append("\n\nREPLACE CHARACTER");
    d.append("\n------------");
    name=name.replace('R','.');
    name=name.replace('O','.');
    d.append("\nname = "+name);
    }
     public void caseConversion(String name1)
    {
    d.append("\n\nCASE CONVERSION");
    d.append("\n------------");
    name1=name1.toLowerCase();
    d.append("\nname1 = "+name1);
    name1=name1.toUpperCase();
    d.append("\nname1 = "+name1);
    String name2=name1.substring(0,1);
    String name3=name1.substring(1,5);
    name2=name2.concat(name3.toLowerCase());
    d.append("\nname2 = "+name2);
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(String1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(String1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(String1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(String1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new String1().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextArea d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}